<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    public function run()
    {
        // ====== Course Categories (Academic Levels) ======
        $categories = [
            [
                'title' => 'Undergraduate Programs',
                'slug' => Str::slug('Undergraduate Programs'),
                'thumbnail' => 'undergraduate-thumbnail.jpg',
                'description' => 'Bachelor degree programs and undergraduate level courses.',
                'icon' => 'undergraduate-icon.png',
                'order_no' => 1,
                'banner_image' => 'undergraduate-banner.jpg',
                'status' => 'publish',
                'isfeature' => 'featured',
                'meta_title' => 'Undergraduate Degree Programs',
                'meta_description' => 'Explore various undergraduate degree programs and specializations.',
                'font_awesome_icon' => 'fa-graduation-cap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Postgraduate Programs',
                'slug' => Str::slug('Postgraduate Programs'),
                'thumbnail' => 'postgraduate-thumbnail.jpg',
                'description' => 'Master degree programs and postgraduate level courses.',
                'icon' => 'postgraduate-icon.png',
                'order_no' => 2,
                'banner_image' => 'postgraduate-banner.jpg',
                'status' => 'publish',
                'isfeature' => 'featured',
                'meta_title' => 'Postgraduate Degree Programs',
                'meta_description' => 'Advance your career with our postgraduate degree programs.',
                'font_awesome_icon' => 'fa-user-graduate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Short Term & Certificate Programs',
                'slug' => Str::slug('Short Term & Certificate Programs'),
                'thumbnail' => 'shortterm-thumbnail.jpg',
                'description' => 'Short-term courses and certificate programs in various domains.',
                'icon' => 'shortterm-icon.png',
                'order_no' => 3,
                'banner_image' => 'shortterm-banner.jpg',
                'status' => 'publish',
                'isfeature' => 'featured',
                'meta_title' => 'Short Term Courses & Certificates',
                'meta_description' => 'Enhance your skills with our short-term and certificate programs.',
                'font_awesome_icon' => 'fa-certificate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('course_categories')->insert($categories);

        // ====== Study Programs (Degree Types) ======
        $studyPrograms = [
            [
                'name' => 'Bachelor of Commerce (B.Com)',
                'slug' => Str::slug('Bachelor of Commerce (B.Com)'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bachelor of Business Administration (BBA)',
                'slug' => Str::slug('Bachelor of Business Administration (BBA)'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bachelor of Computer Applications (BCA)',
                'slug' => Str::slug('Bachelor of Computer Applications (BCA)'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master of Commerce (M.Com)',
                'slug' => Str::slug('Master of Commerce (M.Com)'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master of Business Administration (MBA)',
                'slug' => Str::slug('Master of Business Administration (MBA)'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master of Computer Applications (MCA)',
                'slug' => Str::slug('Master of Computer Applications (MCA)'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Master of Arts (M.A)',
                'slug' => Str::slug('Master of Arts (M.A)'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Short Term IT Courses',
                'slug' => Str::slug('Short Term IT Courses'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Digital Marketing Courses',
                'slug' => Str::slug('Digital Marketing Courses'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Artificial Intelligence Courses',
                'slug' => Str::slug('Artificial Intelligence Courses'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('study_programs')->insert($studyPrograms);

        // ====== Courses ======
        $courses = [
            // Undergraduate Programs (Category ID: 1)
            [
                'course_category_id' => 1,
                'study_program_id' => 1,
                'title' => 'B.Com (General)',
                'slug' => Str::slug('B.Com General'),
                'content' => 'Bachelor of Commerce general program covering fundamental business and commerce subjects.',
                'image' => 'bcom-general.jpg',
                'icon_font' => 'fa-chart-line',
                'icon' => 'bcom-icon.png',
                'banner_image' => 'bcom-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'B.Com, Commerce, Undergraduate',
                'banner_description' => 'Bachelor of Commerce general program for business education.',
                'serial_number' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 1,
                'study_program_id' => 1,
                'title' => 'B.Com in International Finance & Accounting',
                'slug' => Str::slug('B.Com International Finance & Accounting'),
                'content' => 'Specialized B.Com program in International Finance & Accounting accredited by ACCA, UK.',
                'image' => 'bcom-international.jpg',
                'icon_font' => 'fa-globe',
                'icon' => 'bcom-international-icon.png',
                'banner_image' => 'bcom-international-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'B.Com, International Finance, ACCA, Accounting',
                'banner_description' => 'ACCA accredited B.Com in International Finance & Accounting.',
                'serial_number' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 1,
                'study_program_id' => 2,
                'title' => 'BBA (General)',
                'slug' => Str::slug('BBA General'),
                'content' => 'Bachelor of Business Administration general program covering management principles.',
                'image' => 'bba-general.jpg',
                'icon_font' => 'fa-briefcase',
                'icon' => 'bba-icon.png',
                'banner_image' => 'bba-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'BBA, Business Administration, Management',
                'banner_description' => 'Bachelor of Business Administration general program.',
                'serial_number' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 1,
                'study_program_id' => 2,
                'title' => 'BBA in Healthcare Management',
                'slug' => Str::slug('BBA Healthcare Management'),
                'content' => 'Specialized BBA program focusing on healthcare administration and management.',
                'image' => 'bba-healthcare.jpg',
                'icon_font' => 'fa-hospital',
                'icon' => 'bba-healthcare-icon.png',
                'banner_image' => 'bba-healthcare-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'BBA, Healthcare Management, Hospital Administration',
                'banner_description' => 'BBA specialization in Healthcare Management.',
                'serial_number' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // BCA Programs
            [
                'course_category_id' => 1,
                'study_program_id' => 3,
                'title' => 'BCA in Computer Science & Information Technology',
                'slug' => Str::slug('BCA Computer Science & Information Technology'),
                'content' => 'BCA program specializing in Computer Science and Information Technology.',
                'image' => 'bca-csit.jpg',
                'icon_font' => 'fa-laptop-code',
                'icon' => 'bca-csit-icon.png',
                'banner_image' => 'bca-csit-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'BCA, Computer Science, IT',
                'banner_description' => 'BCA in Computer Science & Information Technology.',
                'serial_number' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 1,
                'study_program_id' => 3,
                'title' => 'BCA in Data Science & Analytics',
                'slug' => Str::slug('BCA Data Science & Analytics'),
                'content' => 'BCA program focusing on Data Science, Analytics and Big Data technologies.',
                'image' => 'bca-data-science.jpg',
                'icon_font' => 'fa-chart-bar',
                'icon' => 'bca-data-science-icon.png',
                'banner_image' => 'bca-data-science-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'BCA, Data Science, Analytics, Big Data',
                'banner_description' => 'BCA specialization in Data Science & Analytics.',
                'serial_number' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 1,
                'study_program_id' => 3,
                'title' => 'BCA in Cloud Computing',
                'slug' => Str::slug('BCA Cloud Computing'),
                'content' => 'BCA program specializing in Cloud Computing technologies and platforms.',
                'image' => 'bca-cloud.jpg',
                'icon_font' => 'fa-cloud',
                'icon' => 'bca-cloud-icon.png',
                'banner_image' => 'bca-cloud-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'BCA, Cloud Computing, AWS, Azure',
                'banner_description' => 'BCA in Cloud Computing technologies.',
                'serial_number' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 1,
                'study_program_id' => 3,
                'title' => 'BCA in Cyber Security',
                'slug' => Str::slug('BCA Cyber Security'),
                'content' => 'BCA program focusing on Cyber Security, Network Security and Ethical Hacking.',
                'image' => 'bca-cyber-security.jpg',
                'icon_font' => 'fa-shield-alt',
                'icon' => 'bca-cyber-security-icon.png',
                'banner_image' => 'bca-cyber-security-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'BCA, Cyber Security, Network Security, Ethical Hacking',
                'banner_description' => 'BCA specialization in Cyber Security.',
                'serial_number' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 1,
                'study_program_id' => 3,
                'title' => 'BCA in Artificial Intelligence',
                'slug' => Str::slug('BCA Artificial Intelligence'),
                'content' => 'BCA program specializing in Artificial Intelligence and Machine Learning.',
                'image' => 'bca-ai.jpg',
                'icon_font' => 'fa-robot',
                'icon' => 'bca-ai-icon.png',
                'banner_image' => 'bca-ai-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'BCA, Artificial Intelligence, AI, Machine Learning',
                'banner_description' => 'BCA in Artificial Intelligence and Machine Learning.',
                'serial_number' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Postgraduate Programs (Category ID: 2)
            [
                'course_category_id' => 2,
                'study_program_id' => 4,
                'title' => 'M.Com in Accounting & Finance',
                'slug' => Str::slug('M.Com Accounting & Finance'),
                'content' => 'Master of Commerce program specializing in Accounting and Finance.',
                'image' => 'mcom-accounting.jpg',
                'icon_font' => 'fa-file-invoice-dollar',
                'icon' => 'mcom-accounting-icon.png',
                'banner_image' => 'mcom-accounting-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'M.Com, Accounting, Finance, Postgraduate',
                'banner_description' => 'M.Com specialization in Accounting & Finance.',
                'serial_number' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 4,
                'title' => 'M.Com in International Finance',
                'slug' => Str::slug('M.Com International Finance'),
                'content' => 'M.Com program in International Finance accredited by ACCA, UK.',
                'image' => 'mcom-international.jpg',
                'icon_font' => 'fa-globe-americas',
                'icon' => 'mcom-international-icon.png',
                'banner_image' => 'mcom-international-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'M.Com, International Finance, ACCA',
                'banner_description' => 'ACCA accredited M.Com in International Finance.',
                'serial_number' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // MBA Programs
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Supply Chain, Production and Operations Management',
                'slug' => Str::slug('MBA Supply Chain Production Operations Management'),
                'content' => 'MBA specialization in Supply Chain, Production and Operations Management.',
                'image' => 'mba-supply-chain.jpg',
                'icon_font' => 'fa-truck-loading',
                'icon' => 'mba-supply-chain-icon.png',
                'banner_image' => 'mba-supply-chain-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Supply Chain, Operations Management',
                'banner_description' => 'MBA in Supply Chain and Operations Management.',
                'serial_number' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Human Resource Management',
                'slug' => Str::slug('MBA Human Resource Management'),
                'content' => 'MBA program specializing in Human Resource Management and Organizational Behavior.',
                'image' => 'mba-hr.jpg',
                'icon_font' => 'fa-users',
                'icon' => 'mba-hr-icon.png',
                'banner_image' => 'mba-hr-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Human Resource, HR Management',
                'banner_description' => 'MBA specialization in Human Resource Management.',
                'serial_number' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Finance',
                'slug' => Str::slug('MBA Finance'),
                'content' => 'MBA program focusing on Financial Management, Investment and Corporate Finance.',
                'image' => 'mba-finance.jpg',
                'icon_font' => 'fa-money-bill-wave',
                'icon' => 'mba-finance-icon.png',
                'banner_image' => 'mba-finance-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Finance, Financial Management',
                'banner_description' => 'MBA specialization in Finance.',
                'serial_number' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Marketing',
                'slug' => Str::slug('MBA Marketing'),
                'content' => 'MBA program specializing in Marketing Strategies, Brand Management and Digital Marketing.',
                'image' => 'mba-marketing.jpg',
                'icon_font' => 'fa-bullhorn',
                'icon' => 'mba-marketing-icon.png',
                'banner_image' => 'mba-marketing-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Marketing, Brand Management',
                'banner_description' => 'MBA specialization in Marketing.',
                'serial_number' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in General Management',
                'slug' => Str::slug('MBA General Management'),
                'content' => 'MBA program with comprehensive coverage of general management principles.',
                'image' => 'mba-general.jpg',
                'icon_font' => 'fa-chart-pie',
                'icon' => 'mba-general-icon.png',
                'banner_image' => 'mba-general-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, General Management, Business Administration',
                'banner_description' => 'MBA in General Management.',
                'serial_number' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Retail Management and Quick Commerce',
                'slug' => Str::slug('MBA Retail Management Quick Commerce'),
                'content' => 'MBA program focusing on Retail Management and Quick Commerce business models.',
                'image' => 'mba-retail.jpg',
                'icon_font' => 'fa-shopping-cart',
                'icon' => 'mba-retail-icon.png',
                'banner_image' => 'mba-retail-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Retail Management, Quick Commerce',
                'banner_description' => 'MBA in Retail Management and Quick Commerce.',
                'serial_number' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Finance and Marketing',
                'slug' => Str::slug('MBA Finance and Marketing'),
                'content' => 'Dual specialization MBA program in Finance and Marketing.',
                'image' => 'mba-finance-marketing.jpg',
                'icon_font' => 'fa-hand-holding-usd',
                'icon' => 'mba-finance-marketing-icon.png',
                'banner_image' => 'mba-finance-marketing-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Finance, Marketing, Dual Specialization',
                'banner_description' => 'MBA with dual specialization in Finance and Marketing.',
                'serial_number' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Human Resource Management and Finance',
                'slug' => Str::slug('MBA Human Resource Management and Finance'),
                'content' => 'Dual specialization MBA program in Human Resource Management and Finance.',
                'image' => 'mba-hr-finance.jpg',
                'icon_font' => 'fa-user-tie',
                'icon' => 'mba-hr-finance-icon.png',
                'banner_image' => 'mba-hr-finance-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, HR, Finance, Dual Specialization',
                'banner_description' => 'MBA with dual specialization in HR and Finance.',
                'serial_number' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Marketing and Human Resource Management',
                'slug' => Str::slug('MBA Marketing and Human Resource Management'),
                'content' => 'Dual specialization MBA program in Marketing and Human Resource Management.',
                'image' => 'mba-marketing-hr.jpg',
                'icon_font' => 'fa-bullseye',
                'icon' => 'mba-marketing-hr-icon.png',
                'banner_image' => 'mba-marketing-hr-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Marketing, HR, Dual Specialization',
                'banner_description' => 'MBA with dual specialization in Marketing and HR.',
                'serial_number' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Project Management',
                'slug' => Str::slug('MBA Project Management'),
                'content' => 'MBA program specializing in Project Management methodologies and practices.',
                'image' => 'mba-project.jpg',
                'icon_font' => 'fa-tasks',
                'icon' => 'mba-project-icon.png',
                'banner_image' => 'mba-project-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Project Management, PMP',
                'banner_description' => 'MBA specialization in Project Management.',
                'serial_number' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Information Technology Management',
                'slug' => Str::slug('MBA Information Technology Management'),
                'content' => 'MBA program focusing on IT Management, Systems Analysis and Technology Strategy.',
                'image' => 'mba-it.jpg',
                'icon_font' => 'fa-server',
                'icon' => 'mba-it-icon.png',
                'banner_image' => 'mba-it-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, IT Management, Technology Management',
                'banner_description' => 'MBA in Information Technology Management.',
                'serial_number' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Healthcare Management',
                'slug' => Str::slug('MBA Healthcare Management'),
                'content' => 'MBA program specializing in Healthcare Administration and Hospital Management.',
                'image' => 'mba-healthcare.jpg',
                'icon_font' => 'fa-hospital-user',
                'icon' => 'mba-healthcare-icon.png',
                'banner_image' => 'mba-healthcare-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Healthcare Management, Hospital Administration',
                'banner_description' => 'MBA specialization in Healthcare Management.',
                'serial_number' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Marketing and Business Analytics',
                'slug' => Str::slug('MBA Marketing and Business Analytics'),
                'content' => 'MBA program combining Marketing with Business Analytics and Data-driven decision making.',
                'image' => 'mba-marketing-analytics.jpg',
                'icon_font' => 'fa-chart-line',
                'icon' => 'mba-marketing-analytics-icon.png',
                'banner_image' => 'mba-marketing-analytics-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Marketing, Business Analytics, Data Analysis',
                'banner_description' => 'MBA with Marketing and Business Analytics.',
                'serial_number' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Business Intelligence & Analytics',
                'slug' => Str::slug('MBA Business Intelligence Analytics'),
                'content' => 'MBA program specializing in Business Intelligence, Analytics and Data Visualization.',
                'image' => 'mba-bi.jpg',
                'icon_font' => 'fa-database',
                'icon' => 'mba-bi-icon.png',
                'banner_image' => 'mba-bi-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Business Intelligence, Analytics, BI',
                'banner_description' => 'MBA in Business Intelligence & Analytics.',
                'serial_number' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Entrepreneurship and Venture Creation',
                'slug' => Str::slug('MBA Entrepreneurship and Venture Creation'),
                'content' => 'MBA program focusing on Entrepreneurship, Startup Creation and Venture Development.',
                'image' => 'mba-entrepreneurship.jpg',
                'icon_font' => 'fa-lightbulb',
                'icon' => 'mba-entrepreneurship-icon.png',
                'banner_image' => 'mba-entrepreneurship-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Entrepreneurship, Startup, Venture Creation',
                'banner_description' => 'MBA in Entrepreneurship and Venture Creation.',
                'serial_number' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in International Finance',
                'slug' => Str::slug('MBA International Finance'),
                'content' => 'MBA program in International Finance accredited by ACCA, UK.',
                'image' => 'mba-international-finance.jpg',
                'icon_font' => 'fa-globe',
                'icon' => 'mba-international-finance-icon.png',
                'banner_image' => 'mba-international-finance-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, International Finance, ACCA',
                'banner_description' => 'ACCA accredited MBA in International Finance.',
                'serial_number' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Finance and Business Analytics',
                'slug' => Str::slug('MBA Finance and Business Analytics'),
                'content' => 'MBA program combining Finance with Business Analytics for data-driven financial decisions.',
                'image' => 'mba-finance-analytics.jpg',
                'icon_font' => 'fa-chart-pie',
                'icon' => 'mba-finance-analytics-icon.png',
                'banner_image' => 'mba-finance-analytics-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, Finance, Business Analytics, Financial Analytics',
                'banner_description' => 'MBA with Finance and Business Analytics.',
                'serial_number' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 5,
                'title' => 'MBA in Human Resource and Business Analytics',
                'slug' => Str::slug('MBA Human Resource and Business Analytics'),
                'content' => 'MBA program combining Human Resource Management with Business Analytics.',
                'image' => 'mba-hr-analytics.jpg',
                'icon_font' => 'fa-user-chart',
                'icon' => 'mba-hr-analytics-icon.png',
                'banner_image' => 'mba-hr-analytics-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MBA, HR, Business Analytics, HR Analytics',
                'banner_description' => 'MBA with Human Resource and Business Analytics.',
                'serial_number' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // MCA Programs
            [
                'course_category_id' => 2,
                'study_program_id' => 6,
                'title' => 'MCA in Computer Science & IT',
                'slug' => Str::slug('MCA Computer Science & IT'),
                'content' => 'Master of Computer Applications program in Computer Science and Information Technology.',
                'image' => 'mca-csit.jpg',
                'icon_font' => 'fa-laptop-code',
                'icon' => 'mca-csit-icon.png',
                'banner_image' => 'mca-csit-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MCA, Computer Science, IT, Postgraduate',
                'banner_description' => 'MCA in Computer Science & Information Technology.',
                'serial_number' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 6,
                'title' => 'MCA in Cyber Security',
                'slug' => Str::slug('MCA Cyber Security'),
                'content' => 'MCA program specializing in Cyber Security, Network Defense and Security Management.',
                'image' => 'mca-cyber-security.jpg',
                'icon_font' => 'fa-shield-alt',
                'icon' => 'mca-cyber-security-icon.png',
                'banner_image' => 'mca-cyber-security-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MCA, Cyber Security, Network Security',
                'banner_description' => 'MCA specialization in Cyber Security.',
                'serial_number' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 6,
                'title' => 'MCA in Data Analytics',
                'slug' => Str::slug('MCA Data Analytics'),
                'content' => 'MCA program focusing on Data Analytics, Big Data technologies and Data Mining.',
                'image' => 'mca-data-analytics.jpg',
                'icon_font' => 'fa-chart-bar',
                'icon' => 'mca-data-analytics-icon.png',
                'banner_image' => 'mca-data-analytics-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MCA, Data Analytics, Big Data, Data Mining',
                'banner_description' => 'MCA in Data Analytics.',
                'serial_number' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 6,
                'title' => 'MCA in DevOps',
                'slug' => Str::slug('MCA DevOps'),
                'content' => 'MCA program specializing in DevOps practices, CI/CD pipelines and Cloud Infrastructure.',
                'image' => 'mca-devops.jpg',
                'icon_font' => 'fa-code-branch',
                'icon' => 'mca-devops-icon.png',
                'banner_image' => 'mca-devops-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MCA, DevOps, CI/CD, Cloud',
                'banner_description' => 'MCA specialization in DevOps.',
                'serial_number' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 6,
                'title' => 'MCA in NLP & LLM Development',
                'slug' => Str::slug('MCA NLP LLM Development'),
                'content' => 'MCA program focusing on Natural Language Processing and Large Language Model Development.',
                'image' => 'mca-nlp.jpg',
                'icon_font' => 'fa-brain',
                'icon' => 'mca-nlp-icon.png',
                'banner_image' => 'mca-nlp-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'MCA, NLP, Large Language Models, AI',
                'banner_description' => 'MCA in NLP & LLM Development.',
                'serial_number' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // M.A Programs
            [
                'course_category_id' => 2,
                'study_program_id' => 7,
                'title' => 'M.A in English',
                'slug' => Str::slug('M.A English'),
                'content' => 'Master of Arts program in English Literature and Language Studies.',
                'image' => 'ma-english.jpg',
                'icon_font' => 'fa-book',
                'icon' => 'ma-english-icon.png',
                'banner_image' => 'ma-english-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'M.A, English, Literature, Arts',
                'banner_description' => 'M.A in English Literature and Language.',
                'serial_number' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 7,
                'title' => 'M.A in Public Policy',
                'slug' => Str::slug('M.A Public Policy'),
                'content' => 'Master of Arts program in Public Policy, Governance and Administration.',
                'image' => 'ma-public-policy.jpg',
                'icon_font' => 'fa-landmark',
                'icon' => 'ma-public-policy-icon.png',
                'banner_image' => 'ma-public-policy-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'M.A, Public Policy, Governance',
                'banner_description' => 'M.A in Public Policy.',
                'serial_number' => 36,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 7,
                'title' => 'M.A in Economics',
                'slug' => Str::slug('M.A Economics'),
                'content' => 'Master of Arts program in Economics, Economic Theory and Policy Analysis.',
                'image' => 'ma-economics.jpg',
                'icon_font' => 'fa-chart-line',
                'icon' => 'ma-economics-icon.png',
                'banner_image' => 'ma-economics-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'M.A, Economics, Economic Theory',
                'banner_description' => 'M.A in Economics.',
                'serial_number' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 2,
                'study_program_id' => 7,
                'title' => 'M.A in Jainology and Comparative Religion & Philosophy',
                'slug' => Str::slug('M.A Jainology Comparative Religion Philosophy'),
                'content' => 'Master of Arts program in Jainology, Comparative Religion and Philosophical Studies.',
                'image' => 'ma-jainology.jpg',
                'icon_font' => 'fa-om',
                'icon' => 'ma-jainology-icon.png',
                'banner_image' => 'ma-jainology-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'M.A, Jainology, Comparative Religion, Philosophy',
                'banner_description' => 'M.A in Jainology and Comparative Religion & Philosophy.',
                'serial_number' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Short Term Programs (Category ID: 3)
            [
                'course_category_id' => 3,
                'study_program_id' => 8,
                'title' => 'Web Development Fundamentals',
                'slug' => Str::slug('Web Development Fundamentals'),
                'content' => 'Short-term course covering HTML, CSS, JavaScript and basic web development concepts.',
                'image' => 'web-dev.jpg',
                'icon_font' => 'fa-code',
                'icon' => 'web-dev-icon.png',
                'banner_image' => 'web-dev-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'Web Development, HTML, CSS, JavaScript, Short Term',
                'banner_description' => 'Short-term course in Web Development Fundamentals.',
                'serial_number' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 3,
                'study_program_id' => 8,
                'title' => 'Python Programming',
                'slug' => Str::slug('Python Programming'),
                'content' => 'Short-term course in Python programming language for beginners and intermediates.',
                'image' => 'python.jpg',
                'icon_font' => 'fa-python',
                'icon' => 'python-icon.png',
                'banner_image' => 'python-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'Python, Programming, Short Term',
                'banner_description' => 'Short-term course in Python Programming.',
                'serial_number' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 3,
                'study_program_id' => 8,
                'title' => 'Cloud Computing Basics',
                'slug' => Str::slug('Cloud Computing Basics'),
                'content' => 'Introduction to cloud computing concepts, AWS, Azure and cloud deployment.',
                'image' => 'cloud-basics.jpg',
                'icon_font' => 'fa-cloud',
                'icon' => 'cloud-basics-icon.png',
                'banner_image' => 'cloud-basics-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'Cloud Computing, AWS, Azure, Short Term',
                'banner_description' => 'Short-term course in Cloud Computing Basics.',
                'serial_number' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 3,
                'study_program_id' => 9,
                'title' => 'Digital Marketing Fundamentals',
                'slug' => Str::slug('Digital Marketing Fundamentals'),
                'content' => 'Comprehensive course covering SEO, SEM, Social Media Marketing and Content Marketing.',
                'image' => 'digital-marketing.jpg',
                'icon_font' => 'fa-hashtag',
                'icon' => 'digital-marketing-icon.png',
                'banner_image' => 'digital-marketing-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'Digital Marketing, SEO, SEM, Social Media',
                'banner_description' => 'Short-term course in Digital Marketing Fundamentals.',
                'serial_number' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 3,
                'study_program_id' => 9,
                'title' => 'Social Media Marketing',
                'slug' => Str::slug('Social Media Marketing'),
                'content' => 'Specialized course in Social Media Marketing strategies and campaign management.',
                'image' => 'social-media.jpg',
                'icon_font' => 'fa-share-alt',
                'icon' => 'social-media-icon.png',
                'banner_image' => 'social-media-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'Social Media, Marketing, Facebook, Instagram',
                'banner_description' => 'Short-term course in Social Media Marketing.',
                'serial_number' => 43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 3,
                'study_program_id' => 9,
                'title' => 'Search Engine Optimization (SEO)',
                'slug' => Str::slug('Search Engine Optimization SEO'),
                'content' => 'Comprehensive SEO course covering on-page, off-page and technical SEO techniques.',
                'image' => 'seo.jpg',
                'icon_font' => 'fa-search',
                'icon' => 'seo-icon.png',
                'banner_image' => 'seo-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'SEO, Search Engine Optimization, Digital Marketing',
                'banner_description' => 'Short-term course in Search Engine Optimization.',
                'serial_number' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 3,
                'study_program_id' => 10,
                'title' => 'Introduction to Artificial Intelligence',
                'slug' => Str::slug('Introduction to Artificial Intelligence'),
                'content' => 'Fundamental course covering AI concepts, machine learning basics and AI applications.',
                'image' => 'ai-intro.jpg',
                'icon_font' => 'fa-robot',
                'icon' => 'ai-intro-icon.png',
                'banner_image' => 'ai-intro-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'AI, Artificial Intelligence, Machine Learning',
                'banner_description' => 'Short-term course in Artificial Intelligence fundamentals.',
                'serial_number' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 3,
                'study_program_id' => 10,
                'title' => 'Machine Learning Basics',
                'slug' => Str::slug('Machine Learning Basics'),
                'content' => 'Introduction to machine learning algorithms, data preprocessing and model training.',
                'image' => 'ml-basics.jpg',
                'icon_font' => 'fa-brain',
                'icon' => 'ml-basics-icon.png',
                'banner_image' => 'ml-basics-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'Machine Learning, ML, AI, Data Science',
                'banner_description' => 'Short-term course in Machine Learning Basics.',
                'serial_number' => 46,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_category_id' => 3,
                'study_program_id' => 10,
                'title' => 'Natural Language Processing',
                'slug' => Str::slug('Natural Language Processing'),
                'content' => 'Course covering NLP techniques, text processing and language model applications.',
                'image' => 'nlp.jpg',
                'icon_font' => 'fa-language',
                'icon' => 'nlp-icon.png',
                'banner_image' => 'nlp-banner.jpg',
                'status' => 1,
                'banner_keywords' => 'NLP, Natural Language Processing, AI',
                'banner_description' => 'Short-term course in Natural Language Processing.',
                'serial_number' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('courses')->insert($courses);
    }
}