{{-- ============================================================================
     Why Choose Us partial

     Wave 3 revisions:
       • Animation classes are now generated by index modulo 3, so cards
         beyond the third one ALSO animate (was hardcoded for 0/1/2 only)
       • Removed the per-card "Get Quote" CTA — five identical buttons
         on one screen reads as desperate, not converting. Single CTA at
         the section bottom instead.
       • Icon fallback when $detail->icon is empty (was: broken <img>)
       • Empty-state if section seeded but no details
       • XSS-safe: title and description rendered via {{ }}
       • aria-labelledby on the section
       • Cards tagged role="listitem" inside an aria-list ul
       • Animation skipped when prefers-reduced-motion is on
============================================================================ --}}

@php
    if (!isset($why_choose_us) || !$why_choose_us) return;

    $details = $why_choose_us->details ?? collect();
    $isEN    = app()->getLocale() === 'en';

    $sectionTitle    = trim((string) tr($why_choose_us, 'title'));
    $sectionTagline  = trim((string) tr($why_choose_us, 'subtitle'));
    $sectionDesc     = trim((string) tr($why_choose_us, 'description'));
@endphp

<section class="why-choose-one mt-5" aria-labelledby="why-choose-heading">
    <div class="why-choose-one__shape-1" aria-hidden="true"></div>
    <div class="why-choose-one__shape-2" aria-hidden="true"></div>

    <div class="container">

        <div class="section-title text-center sec-title-animation animation-style2 mb-5">
            @if ($sectionTagline)
                <div class="section-title__tagline-box justify-content-center">
                    <span class="section-title__tagline">{{ $sectionTagline }}</span>
                </div>
            @endif

            @if ($sectionTitle)
                <h2 id="why-choose-heading" class="section-title__title title-animation">
                    {{ $sectionTitle }}
                </h2>
            @endif

            @if ($sectionDesc)
                <p class="sn-prose mx-auto mt-3">
                    {{ strip_tags($sectionDesc) }}
                </p>
            @endif
        </div>

        @if ($details->count() > 0)
            <ul class="row g-4 list-unstyled justify-content-center sn-why-list" role="list">
                @foreach ($details as $index => $detail)
                    @php
                        /* Cycle through 3 animation directions — works for any card count */
                        $animations = ['fadeInLeft', 'fadeInUp', 'fadeInRight'];
                        $animationClass = $animations[$index % 3];
                        $delay = (($index % 3) * 200 + 100) . 'ms';

                        $title    = trim((string) tr($detail, 'title'));
                        $desc     = trim((string) strip_tags(tr($detail, 'description')));
                        $hasIcon  = !empty($detail->icon);
                    @endphp

                    <li class="col-12 col-sm-6 col-lg-4 wow {{ $animationClass }}"
                        data-wow-delay="{{ $delay }}"
                        data-wow-duration="1500ms"
                        role="listitem">

                        <article class="why-choose-one__single h-100 sn-why-card">

                            <div class="why-choose-one__icon">
                                @if ($hasIcon)
                                    <img src="{{ asset($detail->icon) }}"
                                         alt=""
                                         aria-hidden="true"
                                         loading="lazy"
                                         decoding="async"
                                         width="50" height="50">
                                @else
                                    <span class="sn-why-icon-fallback" aria-hidden="true">
                                        <i class="fas fa-shield-alt"></i>
                                    </span>
                                @endif
                            </div>

                            <div class="why-choose-one__single-inner">
                                @if ($title)
                                    <h3 class="why-choose-one__title">{{ $title }}</h3>
                                @endif

                                @if ($desc)
                                    <p class="why-choose-one__text sn-line-clamp-4">
                                        {{ $desc }}
                                    </p>
                                @endif
                            </div>
                        </article>
                    </li>
                @endforeach
            </ul>

            {{-- Single CTA below the cards (was: per-card CTA × N) --}}
            <div class="text-center mt-5">
                <a href="{{ lroute('front.contactus') }}" class="thm-btn thm-btn--lg">
                    {{ $isEN ? 'Get a free quote' : 'Kostenloses Angebot anfordern' }}
                    <span class="fas fa-arrow-right" aria-hidden="true"></span>
                </a>
            </div>
        @endif

    </div>
</section>

@push('scripts')
<style>
    /* Wave 3 polish on top of theme why-choose-one styles */
    .sn-why-card {
        transition:
            transform var(--sn-duration-3) var(--sn-ease),
            box-shadow var(--sn-duration-3) var(--sn-ease);
    }
    .sn-why-card:hover {
        transform: translateY(-4px);
    }

    .sn-why-icon-fallback {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 50px;
        height: 50px;
        border-radius: 50%;
        background: var(--sn-accent-100);
        color: var(--sn-accent-700);
        font-size: 22px;
    }

    .sn-line-clamp-4 {
        display: -webkit-box;
        -webkit-line-clamp: 4;
        line-clamp: 4;
        -webkit-box-orient: vertical;
        overflow: hidden;
    }

    /* Bottom CTA gets a touch of breathing room from the cards */
    .why-choose-one .thm-btn--lg { box-shadow: var(--sn-shadow-md); }
</style>
@endpush
