<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

/**
 * StepNow Rides — explicit helper loader.
 *
 * Why this exists
 * ---------------
 * Helper functions (lroute, lurl, tr, locale_url_for, money, …) live in
 * app/Helpers/*.php as plain procedural functions inside
 * `if (!function_exists(…)) { … }` guards.
 *
 * They will only be available globally if composer.json declares them in
 * "autoload"."files". If composer.json was generated by a tooling step
 * that DOES NOT include those entries (which we have observed in this
 * project after `composer dump-autoload`), the helpers silently disappear,
 * Blade calls them, and either:
 *   - PHP throws "Call to undefined function lroute()" (500 error), or
 *   - Some functions ARE defined (because they were in the bytecode cache)
 *     while others are not, leading to inconsistent rendering — which is
 *     exactly the symptom we see when menu links lose ?lang=en.
 *
 * This provider is THE deterministic fix: it require_once's every PHP
 * file in app/Helpers/ during register(). After this provider runs,
 * EVERY helper is guaranteed to be available, on every request, no
 * matter what composer.json says.
 *
 * Wiring
 * ------
 * Register in bootstrap/providers.php:
 *
 *     return [
 *         App\Providers\AppServiceProvider::class,
 *         App\Providers\HelperServiceProvider::class,    // ← add this
 *         App\Providers\RouteServiceProvider::class,
 *     ];
 */
class HelperServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $dir = app_path('Helpers');
        if (!is_dir($dir)) {
            return;
        }

        // Sort so loading order is deterministic across machines/filesystems
        $files = glob($dir . DIRECTORY_SEPARATOR . '*.php') ?: [];
        sort($files, SORT_STRING);

        foreach ($files as $file) {
            require_once $file;
        }
    }

    public function boot(): void
    {
        // No view-shares or bindings here — just a loader.
    }
}
